@host = http://localhost:5000
@img_path = ./doc/img/factura

### Request to OCR API
POST {{host}}/api/ocr
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="sample_image.jpg"
Content-Type: image/jpeg

< {{img_path}}1.jpg
--MyBoundary--


### Request to Enhance API
POST {{host}}/api/enhance
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="sample_image.jpg"
Content-Type: image/jpeg

< {{img_path}}4.jpg
--MyBoundary--


### Request to auto_correct_perspective API
POST {{host}}/api/auto_correct_perspective
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="sample_image.jpg"
Content-Type: image/jpeg

< ./doc/factura2.jpg
--MyBoundary--
